name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Lint with black through tox
      run: |
        pip install tox
        tox -e black
    - name: Lint with isort through tox
      run: |
        pip install tox
        tox -e isort
    - name: Lint with pylint through tox
      run: |
        pip install tox
        tox -e pylint
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Run tests with pytest
      run: |
        pip install tox
        tox -e py3
  readme-snippets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Run python snippets in README.md
      run: |
        pip install tox
        tox -e byexample
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - name: Build the HTML docs
      run: |
        pip install tox
        tox -e docs
